// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as spotify$0 from "../../github.com/zmb3/spotify/v2/models.js";

export class CurrentlyPlayingTrack {
    "item": spotify$0.SimpleTrack;

    /** Creates a new CurrentlyPlayingTrack instance. */
    constructor($$source: Partial<CurrentlyPlayingTrack> = {}) {
        if (!("item" in $$source)) {
            this["item"] = (new spotify$0.SimpleTrack());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CurrentlyPlayingTrack instance from a string or object.
     */
    static createFrom($$source: any = {}): CurrentlyPlayingTrack {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("item" in $$parsedSource) {
            $$parsedSource["item"] = $$createField0_0($$parsedSource["item"]);
        }
        return new CurrentlyPlayingTrack($$parsedSource as Partial<CurrentlyPlayingTrack>);
    }
}

// Private type creation functions
const $$createType0 = spotify$0.SimpleTrack.createFrom;
