// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as spotify$0 from "../../github.com/zmb3/spotify/v2/models.js";

export class CurrentlyPlayingTrack {
    /**
     * Creates a new CurrentlyPlayingTrack instance.
     * @param {Partial<CurrentlyPlayingTrack>} [$$source = {}] - The source object to create the CurrentlyPlayingTrack.
     */
    constructor($$source = {}) {
        if (!("item" in $$source)) {
            /**
             * @member
             * @type {spotify$0.SimpleTrack}
             */
            this["item"] = (new spotify$0.SimpleTrack());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CurrentlyPlayingTrack instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CurrentlyPlayingTrack}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("item" in $$parsedSource) {
            $$parsedSource["item"] = $$createField0_0($$parsedSource["item"]);
        }
        return new CurrentlyPlayingTrack(/** @type {Partial<CurrentlyPlayingTrack>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = spotify$0.SimpleTrack.createFrom;
