// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddClientID(arg1) {
  return window['go']['backend']['Backend']['AddClientID'](arg1);
}

export function AddClientSecret(arg1) {
  return window['go']['backend']['Backend']['AddClientSecret'](arg1);
}

export function AuthenticateWithSpotify() {
  return window['go']['backend']['Backend']['AuthenticateWithSpotify']();
}

export function ChangeRepeatState(arg1) {
  return window['go']['backend']['Backend']['ChangeRepeatState'](arg1);
}

export function ChangeShuffle(arg1) {
  return window['go']['backend']['Backend']['ChangeShuffle'](arg1);
}

export function CheckIfAuthenticatedWithSpotify() {
  return window['go']['backend']['Backend']['CheckIfAuthenticatedWithSpotify']();
}

export function CloseAuthServer() {
  return window['go']['backend']['Backend']['CloseAuthServer']();
}

export function ExecuteCommand(arg1, arg2) {
  return window['go']['backend']['Backend']['ExecuteCommand'](arg1, arg2);
}

export function GetAlbumsByQuery(arg1) {
  return window['go']['backend']['Backend']['GetAlbumsByQuery'](arg1);
}

export function GetArtistsByQuery(arg1) {
  return window['go']['backend']['Backend']['GetArtistsByQuery'](arg1);
}

export function GetClientID() {
  return window['go']['backend']['Backend']['GetClientID']();
}

export function GetClientSecret() {
  return window['go']['backend']['Backend']['GetClientSecret']();
}

export function GetCurrentlyPlayingTrack() {
  return window['go']['backend']['Backend']['GetCurrentlyPlayingTrack']();
}

export function GetDevices() {
  return window['go']['backend']['Backend']['GetDevices']();
}

export function GetEpisodesByShowID(arg1) {
  return window['go']['backend']['Backend']['GetEpisodesByShowID'](arg1);
}

export function GetPlaylistsByQuery(arg1) {
  return window['go']['backend']['Backend']['GetPlaylistsByQuery'](arg1);
}

export function GetRepeatState() {
  return window['go']['backend']['Backend']['GetRepeatState']();
}

export function GetShowsByQuery(arg1) {
  return window['go']['backend']['Backend']['GetShowsByQuery'](arg1);
}

export function GetSuggestions(arg1, arg2, arg3) {
  return window['go']['backend']['Backend']['GetSuggestions'](arg1, arg2, arg3);
}

export function GetTracksByQuery(arg1) {
  return window['go']['backend']['Backend']['GetTracksByQuery'](arg1);
}

export function GetVolume() {
  return window['go']['backend']['Backend']['GetVolume']();
}

export function IsCurrentSongLiked() {
  return window['go']['backend']['Backend']['IsCurrentSongLiked']();
}

export function IsShuffled() {
  return window['go']['backend']['Backend']['IsShuffled']();
}

export function LikeCurrentSong(arg1) {
  return window['go']['backend']['Backend']['LikeCurrentSong'](arg1);
}

export function Next() {
  return window['go']['backend']['Backend']['Next']();
}

export function Pause() {
  return window['go']['backend']['Backend']['Pause']();
}

export function PlayAlbum(arg1) {
  return window['go']['backend']['Backend']['PlayAlbum'](arg1);
}

export function PlayArtistsTopTracks(arg1) {
  return window['go']['backend']['Backend']['PlayArtistsTopTracks'](arg1);
}

export function PlayPlaylist(arg1) {
  return window['go']['backend']['Backend']['PlayPlaylist'](arg1);
}

export function PlayPodcast(arg1) {
  return window['go']['backend']['Backend']['PlayPodcast'](arg1);
}

export function PlayTrack(arg1) {
  return window['go']['backend']['Backend']['PlayTrack'](arg1);
}

export function Previous() {
  return window['go']['backend']['Backend']['Previous']();
}

export function QueueTrack(arg1) {
  return window['go']['backend']['Backend']['QueueTrack'](arg1);
}

export function Resume() {
  return window['go']['backend']['Backend']['Resume']();
}

export function Seek(arg1) {
  return window['go']['backend']['Backend']['Seek'](arg1);
}

export function SetActiveDevice(arg1) {
  return window['go']['backend']['Backend']['SetActiveDevice'](arg1);
}

export function SetAuthenticatedWithSpotify(arg1) {
  return window['go']['backend']['Backend']['SetAuthenticatedWithSpotify'](arg1);
}

export function SetVolume(arg1) {
  return window['go']['backend']['Backend']['SetVolume'](arg1);
}

export function ShowWindow() {
  return window['go']['backend']['Backend']['ShowWindow']();
}

export function Shuffle(arg1) {
  return window['go']['backend']['Backend']['Shuffle'](arg1);
}
