// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function ExecuteCommand(arg1:string,arg2:{[key: string]: string}):Promise<model.ExecuteActionOutput>;

export function GetSuggestions(arg1:string,arg2:string,arg3:{[key: string]: string}):Promise<model.SuggestionList>;
