// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteCommand(arg1, arg2) {
  return window['go']['backend']['Backend']['ExecuteCommand'](arg1, arg2);
}

export function GetSuggestions(arg1, arg2, arg3) {
  return window['go']['backend']['Backend']['GetSuggestions'](arg1, arg2, arg3);
}
