// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

/**
 * Copyright contains the copyright statement associated with an album.
 */
export class Copyright {
    /**
     * The copyright text for the album.
     */
    "text": string;

    /**
     * The type of copyright.
     */
    "type": string;

    /** Creates a new Copyright instance. */
    constructor($$source: Partial<Copyright> = {}) {
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Copyright instance from a string or object.
     */
    static createFrom($$source: any = {}): Copyright {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Copyright($$parsedSource as Partial<Copyright>);
    }
}

export class EpisodePage {
    /**
     * A URL to a 30 second preview (MP3 format) of the episode.
     */
    "audio_preview_url": string;

    /**
     * A description of the episode.
     */
    "description": string;

    /**
     * The episode length in milliseconds.
     */
    "duration_ms": Numeric;

    /**
     * Whether or not the episode has explicit content
     * (true = yes it does; false = no it does not OR unknown).
     */
    "explicit": boolean;

    /**
     * 	External URLs for this episode.
     */
    "external_urls": { [_: string]: string };

    /**
     * A link to the Web API endpoint providing full details of the episode.
     */
    "href": string;

    /**
     * The Spotify ID for the episode.
     */
    "id": ID;

    /**
     * The cover art for the episode in various sizes, widest first.
     */
    "images": Image[];

    /**
     * True if the episode is hosted outside of Spotify’s CDN.
     */
    "is_externally_hosted": boolean;

    /**
     * True if the episode is playable in the given market.
     * Otherwise false.
     */
    "is_playable": boolean;

    /**
     * A list of the languages used in the episode, identified by their ISO 639 code.
     */
    "languages": string[];

    /**
     * The name of the episode.
     */
    "name": string;

    /**
     * The date the episode was first released, for example
     * "1981-12-15". Depending on the precision, it might
     * be shown as "1981" or "1981-12".
     */
    "release_date": string;

    /**
     * The precision with which release_date value is known:
     * "year", "month", or "day".
     */
    "release_date_precision": string;

    /**
     * The user’s most recent position in the episode. Set if the
     * supplied access token is a user token and has the scope
     * user-read-playback-position.
     */
    "resume_point": ResumePointObject;

    /**
     * The show on which the episode belongs.
     */
    "show": SimpleShow;

    /**
     * The object type: "episode".
     */
    "type": string;

    /**
     * The Spotify URI for the episode.
     */
    "uri": URI;

    /** Creates a new EpisodePage instance. */
    constructor($$source: Partial<EpisodePage> = {}) {
        if (!("audio_preview_url" in $$source)) {
            this["audio_preview_url"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("duration_ms" in $$source)) {
            this["duration_ms"] = (0 as Numeric);
        }
        if (!("explicit" in $$source)) {
            this["explicit"] = false;
        }
        if (!("external_urls" in $$source)) {
            this["external_urls"] = {};
        }
        if (!("href" in $$source)) {
            this["href"] = "";
        }
        if (!("id" in $$source)) {
            this["id"] = ("" as ID);
        }
        if (!("images" in $$source)) {
            this["images"] = [];
        }
        if (!("is_externally_hosted" in $$source)) {
            this["is_externally_hosted"] = false;
        }
        if (!("is_playable" in $$source)) {
            this["is_playable"] = false;
        }
        if (!("languages" in $$source)) {
            this["languages"] = [];
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("release_date" in $$source)) {
            this["release_date"] = "";
        }
        if (!("release_date_precision" in $$source)) {
            this["release_date_precision"] = "";
        }
        if (!("resume_point" in $$source)) {
            this["resume_point"] = (new ResumePointObject());
        }
        if (!("show" in $$source)) {
            this["show"] = (new SimpleShow());
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("uri" in $$source)) {
            this["uri"] = ("" as URI);
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EpisodePage instance from a string or object.
     */
    static createFrom($$source: any = {}): EpisodePage {
        const $$createField4_0 = $$createType0;
        const $$createField7_0 = $$createType2;
        const $$createField10_0 = $$createType3;
        const $$createField14_0 = $$createType4;
        const $$createField15_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("external_urls" in $$parsedSource) {
            $$parsedSource["external_urls"] = $$createField4_0($$parsedSource["external_urls"]);
        }
        if ("images" in $$parsedSource) {
            $$parsedSource["images"] = $$createField7_0($$parsedSource["images"]);
        }
        if ("languages" in $$parsedSource) {
            $$parsedSource["languages"] = $$createField10_0($$parsedSource["languages"]);
        }
        if ("resume_point" in $$parsedSource) {
            $$parsedSource["resume_point"] = $$createField14_0($$parsedSource["resume_point"]);
        }
        if ("show" in $$parsedSource) {
            $$parsedSource["show"] = $$createField15_0($$parsedSource["show"]);
        }
        return new EpisodePage($$parsedSource as Partial<EpisodePage>);
    }
}

/**
 * Followers contains information about the number of people following a
 * particular artist or playlist.
 */
export class Followers {
    /**
     * The total number of followers.
     */
    "total": Numeric;

    /**
     * A link to the Web API endpoint providing full details of the followers,
     * or the empty string if this data is not available.
     */
    "href": string;

    /** Creates a new Followers instance. */
    constructor($$source: Partial<Followers> = {}) {
        if (!("total" in $$source)) {
            this["total"] = (0 as Numeric);
        }
        if (!("href" in $$source)) {
            this["href"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Followers instance from a string or object.
     */
    static createFrom($$source: any = {}): Followers {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Followers($$parsedSource as Partial<Followers>);
    }
}

/**
 * FullArtist provides extra artist data in addition to what is provided by SimpleArtist.
 */
export class FullArtist {
    "name": string;
    "id": ID;

    /**
     * The Spotify URI for the artist.
     */
    "uri": URI;

    /**
     * A link to the Web API endpoint providing full details of the artist.
     */
    "href": string;
    "external_urls": { [_: string]: string };

    /**
     * The popularity of the artist, expressed as an integer between 0 and 100.
     * The artist's popularity is calculated from the popularity of the artist's tracks.
     */
    "popularity": Numeric;

    /**
     * A list of genres the artist is associated with.  For example, "Prog Rock"
     * or "Post-Grunge".  If not yet classified, the slice is empty.
     */
    "genres": string[];
    "followers": Followers;

    /**
     * Images of the artist in various sizes, widest first.
     */
    "images": Image[];

    /** Creates a new FullArtist instance. */
    constructor($$source: Partial<FullArtist> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("id" in $$source)) {
            this["id"] = ("" as ID);
        }
        if (!("uri" in $$source)) {
            this["uri"] = ("" as URI);
        }
        if (!("href" in $$source)) {
            this["href"] = "";
        }
        if (!("external_urls" in $$source)) {
            this["external_urls"] = {};
        }
        if (!("popularity" in $$source)) {
            this["popularity"] = (0 as Numeric);
        }
        if (!("genres" in $$source)) {
            this["genres"] = [];
        }
        if (!("followers" in $$source)) {
            this["followers"] = (new Followers());
        }
        if (!("images" in $$source)) {
            this["images"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FullArtist instance from a string or object.
     */
    static createFrom($$source: any = {}): FullArtist {
        const $$createField4_0 = $$createType0;
        const $$createField6_0 = $$createType3;
        const $$createField7_0 = $$createType6;
        const $$createField8_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("external_urls" in $$parsedSource) {
            $$parsedSource["external_urls"] = $$createField4_0($$parsedSource["external_urls"]);
        }
        if ("genres" in $$parsedSource) {
            $$parsedSource["genres"] = $$createField6_0($$parsedSource["genres"]);
        }
        if ("followers" in $$parsedSource) {
            $$parsedSource["followers"] = $$createField7_0($$parsedSource["followers"]);
        }
        if ("images" in $$parsedSource) {
            $$parsedSource["images"] = $$createField8_0($$parsedSource["images"]);
        }
        return new FullArtist($$parsedSource as Partial<FullArtist>);
    }
}

/**
 * FullShow contains full data about a show.
 */
export class FullShow {
    /**
     * A list of the countries in which the show can be played,
     * identified by their ISO 3166-1 alpha-2 code.
     */
    "available_markets": string[];

    /**
     * The copyright statements of the show.
     */
    "copyrights": Copyright[];

    /**
     * A description of the show.
     */
    "description": string;

    /**
     * Whether or not the show has explicit content
     * (true = yes it does; false = no it does not OR unknown).
     */
    "explicit": boolean;

    /**
     * Known external URLs for this show.
     */
    "external_urls": { [_: string]: string };

    /**
     * A link to the Web API endpoint providing full details
     * of the show.
     */
    "href": string;

    /**
     * The SpotifyID for the show.
     */
    "id": ID;

    /**
     * The cover art for the show in various sizes,
     * widest first.
     */
    "images": Image[];

    /**
     * True if all of the show’s episodes are hosted outside
     * of Spotify’s CDN. This field might be null in some cases.
     */
    "is_externally_hosted": boolean | null;

    /**
     * A list of the languages used in the show, identified by
     * their ISO 639 code.
     */
    "languages": string[];

    /**
     * The media type of the show.
     */
    "media_type": string;

    /**
     * The name of the show.
     */
    "name": string;

    /**
     * The publisher of the show.
     */
    "publisher": string;

    /**
     * The object type: “show”.
     */
    "type": string;

    /**
     * The Spotify URI for the show.
     */
    "uri": URI;

    /**
     * A list of the show’s episodes.
     */
    "episodes": SimpleEpisodePage;

    /** Creates a new FullShow instance. */
    constructor($$source: Partial<FullShow> = {}) {
        if (!("available_markets" in $$source)) {
            this["available_markets"] = [];
        }
        if (!("copyrights" in $$source)) {
            this["copyrights"] = [];
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("explicit" in $$source)) {
            this["explicit"] = false;
        }
        if (!("external_urls" in $$source)) {
            this["external_urls"] = {};
        }
        if (!("href" in $$source)) {
            this["href"] = "";
        }
        if (!("id" in $$source)) {
            this["id"] = ("" as ID);
        }
        if (!("images" in $$source)) {
            this["images"] = [];
        }
        if (!("is_externally_hosted" in $$source)) {
            this["is_externally_hosted"] = null;
        }
        if (!("languages" in $$source)) {
            this["languages"] = [];
        }
        if (!("media_type" in $$source)) {
            this["media_type"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("publisher" in $$source)) {
            this["publisher"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("uri" in $$source)) {
            this["uri"] = ("" as URI);
        }
        if (!("episodes" in $$source)) {
            this["episodes"] = (new SimpleEpisodePage());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FullShow instance from a string or object.
     */
    static createFrom($$source: any = {}): FullShow {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType8;
        const $$createField4_0 = $$createType0;
        const $$createField7_0 = $$createType2;
        const $$createField9_0 = $$createType3;
        const $$createField15_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("available_markets" in $$parsedSource) {
            $$parsedSource["available_markets"] = $$createField0_0($$parsedSource["available_markets"]);
        }
        if ("copyrights" in $$parsedSource) {
            $$parsedSource["copyrights"] = $$createField1_0($$parsedSource["copyrights"]);
        }
        if ("external_urls" in $$parsedSource) {
            $$parsedSource["external_urls"] = $$createField4_0($$parsedSource["external_urls"]);
        }
        if ("images" in $$parsedSource) {
            $$parsedSource["images"] = $$createField7_0($$parsedSource["images"]);
        }
        if ("languages" in $$parsedSource) {
            $$parsedSource["languages"] = $$createField9_0($$parsedSource["languages"]);
        }
        if ("episodes" in $$parsedSource) {
            $$parsedSource["episodes"] = $$createField15_0($$parsedSource["episodes"]);
        }
        return new FullShow($$parsedSource as Partial<FullShow>);
    }
}

/**
 * ID is a base-62 identifier for an artist, track, album, etc.
 * It can be found at the end of a spotify.URI.
 */
export type ID = string;

/**
 * Image identifies an image associated with an item.
 */
export class Image {
    /**
     * The image height, in pixels.
     */
    "height": Numeric;

    /**
     * The image width, in pixels.
     */
    "width": Numeric;

    /**
     * The source URL of the image.
     */
    "url": string;

    /** Creates a new Image instance. */
    constructor($$source: Partial<Image> = {}) {
        if (!("height" in $$source)) {
            this["height"] = (0 as Numeric);
        }
        if (!("width" in $$source)) {
            this["width"] = (0 as Numeric);
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Image instance from a string or object.
     */
    static createFrom($$source: any = {}): Image {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Image($$parsedSource as Partial<Image>);
    }
}

/**
 * Numeric is a convenience type for handling numbers sent as either integers or floats.
 */
export type Numeric = number;

export class PlayOptions {
    /**
     * PlaybackContext Spotify URI of the context to play.
     * Valid contexts are albums, artists & playlists.
     */
    "context_uri"?: URI | null;

    /**
     * URIs Array of the Spotify track URIs to play
     */
    "uris"?: URI[];

    /**
     * PlaybackOffset Indicates from where in the context playback should start.
     * Only available when context corresponds to an album or playlist
     * object, or when the URIs parameter is used.
     */
    "offset"?: PlaybackOffset | null;

    /**
     * PositionMs Indicates from what position to start playback.
     * Must be a positive number. Passing in a position that is greater
     * than the length of the track will cause the player to start playing the next song.
     * Defaults to 0, starting a track from the beginning.
     */
    "position_ms"?: Numeric;

    /** Creates a new PlayOptions instance. */
    constructor($$source: Partial<PlayOptions> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlayOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): PlayOptions {
        const $$createField1_0 = $$createType10;
        const $$createField2_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("uris" in $$parsedSource) {
            $$parsedSource["uris"] = $$createField1_0($$parsedSource["uris"]);
        }
        if ("offset" in $$parsedSource) {
            $$parsedSource["offset"] = $$createField2_0($$parsedSource["offset"]);
        }
        return new PlayOptions($$parsedSource as Partial<PlayOptions>);
    }
}

/**
 * PlaybackOffset can be specified either by track URI OR Position. If the
 * Position field is set to a non-nil pointer, it will be taken into
 * consideration when specifying the playback offset. If the Position field is
 * set to a nil pointer, it will be ignored and only the URI will be used to
 * specify the offset. If both are present the request will return 400 BAD
 * REQUEST. If incorrect values are provided for position or uri, the request
 * may be accepted but with an unpredictable resulting action on playback.
 */
export class PlaybackOffset {
    /**
     * Position is zero based and can’t be negative.
     */
    "position"?: number | null;

    /**
     * URI is a string representing the uri of the item to start at.
     */
    "uri"?: URI;

    /** Creates a new PlaybackOffset instance. */
    constructor($$source: Partial<PlaybackOffset> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlaybackOffset instance from a string or object.
     */
    static createFrom($$source: any = {}): PlaybackOffset {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlaybackOffset($$parsedSource as Partial<PlaybackOffset>);
    }
}

/**
 * PlayerDevice contains information about a device that a user can play music on
 */
export class PlayerDevice {
    /**
     * ID of the device. This may be empty.
     */
    "id": ID;

    /**
     * Active If this device is the currently active device.
     */
    "is_active": boolean;

    /**
     * Restricted Whether controlling this device is restricted. At present if
     * this is "true" then no Web API commands will be accepted by this device.
     */
    "is_restricted": boolean;

    /**
     * Name The name of the device.
     */
    "name": string;

    /**
     * Type of device, such as "Computer", "Smartphone" or "Speaker".
     */
    "type": string;

    /**
     * Volume The current volume in percent.
     */
    "volume_percent": Numeric;

    /** Creates a new PlayerDevice instance. */
    constructor($$source: Partial<PlayerDevice> = {}) {
        if (!("id" in $$source)) {
            this["id"] = ("" as ID);
        }
        if (!("is_active" in $$source)) {
            this["is_active"] = false;
        }
        if (!("is_restricted" in $$source)) {
            this["is_restricted"] = false;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("volume_percent" in $$source)) {
            this["volume_percent"] = (0 as Numeric);
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlayerDevice instance from a string or object.
     */
    static createFrom($$source: any = {}): PlayerDevice {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlayerDevice($$parsedSource as Partial<PlayerDevice>);
    }
}

/**
 * PlaylistTracks contains details about the tracks in a playlist.
 */
export class PlaylistTracks {
    /**
     * A link to the Web API endpoint where full details of
     * the playlist's tracks can be retrieved.
     */
    "href": string;

    /**
     * The total number of tracks in the playlist.
     */
    "total": Numeric;

    /** Creates a new PlaylistTracks instance. */
    constructor($$source: Partial<PlaylistTracks> = {}) {
        if (!("href" in $$source)) {
            this["href"] = "";
        }
        if (!("total" in $$source)) {
            this["total"] = (0 as Numeric);
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlaylistTracks instance from a string or object.
     */
    static createFrom($$source: any = {}): PlaylistTracks {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlaylistTracks($$parsedSource as Partial<PlaylistTracks>);
    }
}

export class ResumePointObject {
    /**
     * 	Whether or not the episode has been fully played by the user.
     */
    "fully_played": boolean;

    /**
     * The user’s most recent position in the episode in milliseconds.
     */
    "resume_position_ms": Numeric;

    /** Creates a new ResumePointObject instance. */
    constructor($$source: Partial<ResumePointObject> = {}) {
        if (!("fully_played" in $$source)) {
            this["fully_played"] = false;
        }
        if (!("resume_position_ms" in $$source)) {
            this["resume_position_ms"] = (0 as Numeric);
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResumePointObject instance from a string or object.
     */
    static createFrom($$source: any = {}): ResumePointObject {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResumePointObject($$parsedSource as Partial<ResumePointObject>);
    }
}

/**
 * SimpleAlbum contains basic data about an album.
 */
export class SimpleAlbum {
    /**
     * The name of the album.
     */
    "name": string;

    /**
     * A slice of SimpleArtists
     */
    "artists": SimpleArtist[];

    /**
     * The field is present when getting an artist’s
     * albums. Possible values are “album”, “single”,
     * “compilation”, “appears_on”. Compare to album_type
     * this field represents relationship between the artist
     * and the album.
     */
    "album_group": string;

    /**
     * The type of the album: one of "album",
     * "single", or "compilation".
     */
    "album_type": string;

    /**
     * The SpotifyID for the album.
     */
    "id": ID;

    /**
     * The SpotifyURI for the album.
     */
    "uri": URI;

    /**
     * The markets in which the album is available,
     * identified using ISO 3166-1 alpha-2 country
     * codes.  Note that al album is considered
     * available in a market when at least 1 of its
     * tracks is available in that market.
     */
    "available_markets": string[];

    /**
     * A link to the Web API endpoint providing full
     * details of the album.
     */
    "href": string;

    /**
     * The cover art for the album in various sizes,
     * widest first.
     */
    "images": Image[];

    /**
     * Known external URLs for this album.
     */
    "external_urls": { [_: string]: string };

    /**
     * The date the album was first released.  For example, "1981-12-15".
     * Depending on the ReleaseDatePrecision, it might be shown as
     * "1981" or "1981-12". You can use ReleaseDateTime to convert this
     * to a time.Time value.
     */
    "release_date": string;

    /**
     * The precision with which ReleaseDate value is known: "year", "month", or "day"
     */
    "release_date_precision": string;

    /** Creates a new SimpleAlbum instance. */
    constructor($$source: Partial<SimpleAlbum> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("artists" in $$source)) {
            this["artists"] = [];
        }
        if (!("album_group" in $$source)) {
            this["album_group"] = "";
        }
        if (!("album_type" in $$source)) {
            this["album_type"] = "";
        }
        if (!("id" in $$source)) {
            this["id"] = ("" as ID);
        }
        if (!("uri" in $$source)) {
            this["uri"] = ("" as URI);
        }
        if (!("available_markets" in $$source)) {
            this["available_markets"] = [];
        }
        if (!("href" in $$source)) {
            this["href"] = "";
        }
        if (!("images" in $$source)) {
            this["images"] = [];
        }
        if (!("external_urls" in $$source)) {
            this["external_urls"] = {};
        }
        if (!("release_date" in $$source)) {
            this["release_date"] = "";
        }
        if (!("release_date_precision" in $$source)) {
            this["release_date_precision"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SimpleAlbum instance from a string or object.
     */
    static createFrom($$source: any = {}): SimpleAlbum {
        const $$createField1_0 = $$createType14;
        const $$createField6_0 = $$createType3;
        const $$createField8_0 = $$createType2;
        const $$createField9_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("artists" in $$parsedSource) {
            $$parsedSource["artists"] = $$createField1_0($$parsedSource["artists"]);
        }
        if ("available_markets" in $$parsedSource) {
            $$parsedSource["available_markets"] = $$createField6_0($$parsedSource["available_markets"]);
        }
        if ("images" in $$parsedSource) {
            $$parsedSource["images"] = $$createField8_0($$parsedSource["images"]);
        }
        if ("external_urls" in $$parsedSource) {
            $$parsedSource["external_urls"] = $$createField9_0($$parsedSource["external_urls"]);
        }
        return new SimpleAlbum($$parsedSource as Partial<SimpleAlbum>);
    }
}

/**
 * SimpleArtist contains basic info about an artist.
 */
export class SimpleArtist {
    "name": string;
    "id": ID;

    /**
     * The Spotify URI for the artist.
     */
    "uri": URI;

    /**
     * A link to the Web API endpoint providing full details of the artist.
     */
    "href": string;
    "external_urls": { [_: string]: string };

    /** Creates a new SimpleArtist instance. */
    constructor($$source: Partial<SimpleArtist> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("id" in $$source)) {
            this["id"] = ("" as ID);
        }
        if (!("uri" in $$source)) {
            this["uri"] = ("" as URI);
        }
        if (!("href" in $$source)) {
            this["href"] = "";
        }
        if (!("external_urls" in $$source)) {
            this["external_urls"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SimpleArtist instance from a string or object.
     */
    static createFrom($$source: any = {}): SimpleArtist {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("external_urls" in $$parsedSource) {
            $$parsedSource["external_urls"] = $$createField4_0($$parsedSource["external_urls"]);
        }
        return new SimpleArtist($$parsedSource as Partial<SimpleArtist>);
    }
}

/**
 * SimpleEpisodePage contains EpisodePage returned by the Web API.
 */
export class SimpleEpisodePage {
    /**
     * A link to the Web API Endpoint returning the full
     * result of this request.
     */
    "href": string;

    /**
     * The maximum number of items in the response, as set
     * in the query (or default value if unset).
     */
    "limit": Numeric;

    /**
     * The offset of the items returned, as set in the query
     * (or default value if unset).
     */
    "offset": Numeric;

    /**
     * The total number of items available to return.
     */
    "total": Numeric;

    /**
     * The URL to the next page of items (if available).
     */
    "next": string;

    /**
     * The URL to the previous page of items (if available).
     */
    "previous": string;
    "items": EpisodePage[];

    /** Creates a new SimpleEpisodePage instance. */
    constructor($$source: Partial<SimpleEpisodePage> = {}) {
        if (!("href" in $$source)) {
            this["href"] = "";
        }
        if (!("limit" in $$source)) {
            this["limit"] = (0 as Numeric);
        }
        if (!("offset" in $$source)) {
            this["offset"] = (0 as Numeric);
        }
        if (!("total" in $$source)) {
            this["total"] = (0 as Numeric);
        }
        if (!("next" in $$source)) {
            this["next"] = "";
        }
        if (!("previous" in $$source)) {
            this["previous"] = "";
        }
        if (!("items" in $$source)) {
            this["items"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SimpleEpisodePage instance from a string or object.
     */
    static createFrom($$source: any = {}): SimpleEpisodePage {
        const $$createField6_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField6_0($$parsedSource["items"]);
        }
        return new SimpleEpisodePage($$parsedSource as Partial<SimpleEpisodePage>);
    }
}

/**
 * SimplePlaylist contains basic info about a Spotify playlist.
 */
export class SimplePlaylist {
    /**
     * Indicates whether the playlist owner allows others to modify the playlist.
     * Note: only non-collaborative playlists are currently returned by Spotify's Web API.
     */
    "collaborative": boolean;

    /**
     * The playlist description. Empty string if no description is set.
     */
    "description": string;
    "external_urls": { [_: string]: string };

    /**
     * A link to the Web API endpoint providing full details of the playlist.
     */
    "href": string;
    "id": ID;

    /**
     * The playlist image.  Note: this field is only  returned for modified,
     * verified playlists. Otherwise the slice is empty.  If returned, the source
     * URL for the image is temporary and will expire in less than a day.
     */
    "images": Image[];
    "name": string;
    "owner": User;
    "public": boolean;

    /**
     * The version identifier for the current playlist. Can be supplied in other
     * requests to target a specific playlist version.
     */
    "snapshot_id": string;

    /**
     * A collection to the Web API endpoint where full details of the playlist's
     * tracks can be retrieved, along with the total number of tracks in the playlist.
     */
    "tracks": PlaylistTracks;
    "uri": URI;

    /** Creates a new SimplePlaylist instance. */
    constructor($$source: Partial<SimplePlaylist> = {}) {
        if (!("collaborative" in $$source)) {
            this["collaborative"] = false;
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("external_urls" in $$source)) {
            this["external_urls"] = {};
        }
        if (!("href" in $$source)) {
            this["href"] = "";
        }
        if (!("id" in $$source)) {
            this["id"] = ("" as ID);
        }
        if (!("images" in $$source)) {
            this["images"] = [];
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("owner" in $$source)) {
            this["owner"] = (new User());
        }
        if (!("public" in $$source)) {
            this["public"] = false;
        }
        if (!("snapshot_id" in $$source)) {
            this["snapshot_id"] = "";
        }
        if (!("tracks" in $$source)) {
            this["tracks"] = (new PlaylistTracks());
        }
        if (!("uri" in $$source)) {
            this["uri"] = ("" as URI);
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SimplePlaylist instance from a string or object.
     */
    static createFrom($$source: any = {}): SimplePlaylist {
        const $$createField2_0 = $$createType0;
        const $$createField5_0 = $$createType2;
        const $$createField7_0 = $$createType17;
        const $$createField10_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("external_urls" in $$parsedSource) {
            $$parsedSource["external_urls"] = $$createField2_0($$parsedSource["external_urls"]);
        }
        if ("images" in $$parsedSource) {
            $$parsedSource["images"] = $$createField5_0($$parsedSource["images"]);
        }
        if ("owner" in $$parsedSource) {
            $$parsedSource["owner"] = $$createField7_0($$parsedSource["owner"]);
        }
        if ("tracks" in $$parsedSource) {
            $$parsedSource["tracks"] = $$createField10_0($$parsedSource["tracks"]);
        }
        return new SimplePlaylist($$parsedSource as Partial<SimplePlaylist>);
    }
}

/**
 * SimpleShow contains basic data about a show.
 */
export class SimpleShow {
    /**
     * A list of the countries in which the show can be played,
     * identified by their ISO 3166-1 alpha-2 code.
     */
    "available_markets": string[];

    /**
     * The copyright statements of the show.
     */
    "copyrights": Copyright[];

    /**
     * A description of the show.
     */
    "description": string;

    /**
     * Whether or not the show has explicit content
     * (true = yes it does; false = no it does not OR unknown).
     */
    "explicit": boolean;

    /**
     * Known external URLs for this show.
     */
    "external_urls": { [_: string]: string };

    /**
     * A link to the Web API endpoint providing full details
     * of the show.
     */
    "href": string;

    /**
     * The SpotifyID for the show.
     */
    "id": ID;

    /**
     * The cover art for the show in various sizes,
     * widest first.
     */
    "images": Image[];

    /**
     * True if all of the show’s episodes are hosted outside
     * of Spotify’s CDN. This field might be null in some cases.
     */
    "is_externally_hosted": boolean | null;

    /**
     * A list of the languages used in the show, identified by
     * their ISO 639 code.
     */
    "languages": string[];

    /**
     * The media type of the show.
     */
    "media_type": string;

    /**
     * The name of the show.
     */
    "name": string;

    /**
     * The publisher of the show.
     */
    "publisher": string;

    /**
     * The object type: “show”.
     */
    "type": string;

    /**
     * The Spotify URI for the show.
     */
    "uri": URI;

    /** Creates a new SimpleShow instance. */
    constructor($$source: Partial<SimpleShow> = {}) {
        if (!("available_markets" in $$source)) {
            this["available_markets"] = [];
        }
        if (!("copyrights" in $$source)) {
            this["copyrights"] = [];
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("explicit" in $$source)) {
            this["explicit"] = false;
        }
        if (!("external_urls" in $$source)) {
            this["external_urls"] = {};
        }
        if (!("href" in $$source)) {
            this["href"] = "";
        }
        if (!("id" in $$source)) {
            this["id"] = ("" as ID);
        }
        if (!("images" in $$source)) {
            this["images"] = [];
        }
        if (!("is_externally_hosted" in $$source)) {
            this["is_externally_hosted"] = null;
        }
        if (!("languages" in $$source)) {
            this["languages"] = [];
        }
        if (!("media_type" in $$source)) {
            this["media_type"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("publisher" in $$source)) {
            this["publisher"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("uri" in $$source)) {
            this["uri"] = ("" as URI);
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SimpleShow instance from a string or object.
     */
    static createFrom($$source: any = {}): SimpleShow {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType8;
        const $$createField4_0 = $$createType0;
        const $$createField7_0 = $$createType2;
        const $$createField9_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("available_markets" in $$parsedSource) {
            $$parsedSource["available_markets"] = $$createField0_0($$parsedSource["available_markets"]);
        }
        if ("copyrights" in $$parsedSource) {
            $$parsedSource["copyrights"] = $$createField1_0($$parsedSource["copyrights"]);
        }
        if ("external_urls" in $$parsedSource) {
            $$parsedSource["external_urls"] = $$createField4_0($$parsedSource["external_urls"]);
        }
        if ("images" in $$parsedSource) {
            $$parsedSource["images"] = $$createField7_0($$parsedSource["images"]);
        }
        if ("languages" in $$parsedSource) {
            $$parsedSource["languages"] = $$createField9_0($$parsedSource["languages"]);
        }
        return new SimpleShow($$parsedSource as Partial<SimpleShow>);
    }
}

/**
 * SimpleTrack contains basic info about a track.
 */
export class SimpleTrack {
    "album": SimpleAlbum;
    "artists": SimpleArtist[];

    /**
     * A list of the countries in which the track can be played,
     * identified by their ISO 3166-1 alpha-2 codes.
     */
    "available_markets": string[];

    /**
     * The disc number (usually 1 unless the album consists of more than one disc).
     */
    "disc_number": Numeric;

    /**
     * The length of the track, in milliseconds.
     */
    "duration_ms": Numeric;

    /**
     * Whether or not the track has explicit lyrics.
     * true => yes, it does; false => no, it does not.
     */
    "explicit": boolean;

    /**
     * External URLs for this track.
     */
    "external_urls": { [_: string]: string };

    /**
     * ExternalIDs are IDs for this track in other databases
     */
    "external_ids": TrackExternalIDs;

    /**
     * A link to the Web API endpoint providing full details for this track.
     */
    "href": string;
    "id": ID;
    "name": string;

    /**
     * A URL to a 30 second preview (MP3) of the track.
     */
    "preview_url": string;

    /**
     * The number of the track.  If an album has several
     * discs, the track number is the number on the specified
     * DiscNumber.
     */
    "track_number": Numeric;
    "uri": URI;

    /**
     * Type of the track
     */
    "type": string;

    /** Creates a new SimpleTrack instance. */
    constructor($$source: Partial<SimpleTrack> = {}) {
        if (!("album" in $$source)) {
            this["album"] = (new SimpleAlbum());
        }
        if (!("artists" in $$source)) {
            this["artists"] = [];
        }
        if (!("available_markets" in $$source)) {
            this["available_markets"] = [];
        }
        if (!("disc_number" in $$source)) {
            this["disc_number"] = (0 as Numeric);
        }
        if (!("duration_ms" in $$source)) {
            this["duration_ms"] = (0 as Numeric);
        }
        if (!("explicit" in $$source)) {
            this["explicit"] = false;
        }
        if (!("external_urls" in $$source)) {
            this["external_urls"] = {};
        }
        if (!("external_ids" in $$source)) {
            this["external_ids"] = (new TrackExternalIDs());
        }
        if (!("href" in $$source)) {
            this["href"] = "";
        }
        if (!("id" in $$source)) {
            this["id"] = ("" as ID);
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("preview_url" in $$source)) {
            this["preview_url"] = "";
        }
        if (!("track_number" in $$source)) {
            this["track_number"] = (0 as Numeric);
        }
        if (!("uri" in $$source)) {
            this["uri"] = ("" as URI);
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SimpleTrack instance from a string or object.
     */
    static createFrom($$source: any = {}): SimpleTrack {
        const $$createField0_0 = $$createType19;
        const $$createField1_0 = $$createType14;
        const $$createField2_0 = $$createType3;
        const $$createField6_0 = $$createType0;
        const $$createField7_0 = $$createType20;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("album" in $$parsedSource) {
            $$parsedSource["album"] = $$createField0_0($$parsedSource["album"]);
        }
        if ("artists" in $$parsedSource) {
            $$parsedSource["artists"] = $$createField1_0($$parsedSource["artists"]);
        }
        if ("available_markets" in $$parsedSource) {
            $$parsedSource["available_markets"] = $$createField2_0($$parsedSource["available_markets"]);
        }
        if ("external_urls" in $$parsedSource) {
            $$parsedSource["external_urls"] = $$createField6_0($$parsedSource["external_urls"]);
        }
        if ("external_ids" in $$parsedSource) {
            $$parsedSource["external_ids"] = $$createField7_0($$parsedSource["external_ids"]);
        }
        return new SimpleTrack($$parsedSource as Partial<SimpleTrack>);
    }
}

export class TrackExternalIDs {
    "isrc": string;
    "ean": string;
    "upc": string;

    /** Creates a new TrackExternalIDs instance. */
    constructor($$source: Partial<TrackExternalIDs> = {}) {
        if (!("isrc" in $$source)) {
            this["isrc"] = "";
        }
        if (!("ean" in $$source)) {
            this["ean"] = "";
        }
        if (!("upc" in $$source)) {
            this["upc"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TrackExternalIDs instance from a string or object.
     */
    static createFrom($$source: any = {}): TrackExternalIDs {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TrackExternalIDs($$parsedSource as Partial<TrackExternalIDs>);
    }
}

/**
 * URI identifies an artist, album, track, or category.  For example,
 * spotify:track:6rqhFgbbKwnb9MLmUQDhG6
 */
export type URI = string;

/**
 * User contains the basic, publicly available information about a Spotify user.
 */
export class User {
    /**
     * The name displayed on the user's profile.
     * Note: Spotify currently fails to populate
     * this field when querying for a playlist.
     */
    "display_name": string;

    /**
     * Known public external URLs for the user.
     */
    "external_urls": { [_: string]: string };

    /**
     * Information about followers of the user.
     */
    "followers": Followers;

    /**
     * A link to the Web API endpoint for this user.
     */
    "href": string;

    /**
     * The Spotify user ID for the user.
     */
    "id": string;

    /**
     * The user's profile image.
     */
    "images": Image[];

    /**
     * The Spotify URI for the user.
     */
    "uri": URI;

    /** Creates a new User instance. */
    constructor($$source: Partial<User> = {}) {
        if (!("display_name" in $$source)) {
            this["display_name"] = "";
        }
        if (!("external_urls" in $$source)) {
            this["external_urls"] = {};
        }
        if (!("followers" in $$source)) {
            this["followers"] = (new Followers());
        }
        if (!("href" in $$source)) {
            this["href"] = "";
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("images" in $$source)) {
            this["images"] = [];
        }
        if (!("uri" in $$source)) {
            this["uri"] = ("" as URI);
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new User instance from a string or object.
     */
    static createFrom($$source: any = {}): User {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType6;
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("external_urls" in $$parsedSource) {
            $$parsedSource["external_urls"] = $$createField1_0($$parsedSource["external_urls"]);
        }
        if ("followers" in $$parsedSource) {
            $$parsedSource["followers"] = $$createField2_0($$parsedSource["followers"]);
        }
        if ("images" in $$parsedSource) {
            $$parsedSource["images"] = $$createField5_0($$parsedSource["images"]);
        }
        return new User($$parsedSource as Partial<User>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = Image.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = ResumePointObject.createFrom;
const $$createType5 = SimpleShow.createFrom;
const $$createType6 = Followers.createFrom;
const $$createType7 = Copyright.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = SimpleEpisodePage.createFrom;
const $$createType10 = $Create.Array($Create.Any);
const $$createType11 = PlaybackOffset.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = SimpleArtist.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = EpisodePage.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = User.createFrom;
const $$createType18 = PlaylistTracks.createFrom;
const $$createType19 = SimpleAlbum.createFrom;
const $$createType20 = TrackExternalIDs.createFrom;
